module.exports = {
  purge: {
    enabled: process.env.NODE_ENV !== 'development',
    content: ['./src/**/*.html', './src/**/*.jsx', './src/**/*.js'],
    options: {
      safelist: [
        'sm:ml-3',
        'sm:mr-3',
        'l-3',
        'r-3',
        'rtl',
        'ltr',
        'pl-10',
        'pr-10',
        'lg:text-right',
        'lg:text-left',
        'right',
        'left',
        'ml-1',
        'ml-1',
        'mr-2',
        'mr-2',
      ],
      keyframes: true,
    },
  },
  theme: {
    extend: {
      fontFamily: {
        sans: ['NotoSwahili'],
        ar: ['Noto'],
        'ar-title': ['NotoKufi'],
        am: ['NotoEthio'],
      },
      colors: {
        'language-ar': '#064E3B',
        'language-am': '#DC2626',
        'language-sw': '#78350F',
        'language-en': '#4B5563',
      },
    },
    opacity: {
      0: '0',
      10: '.1',
      20: '.2',
      30: '.3',
      40: '.4',
      50: '.5',
      60: '.6',
      70: '.7',
      80: '.8',
      90: '.9',
      100: '1',
    },
  },
  variants: {},
  plugins: [],
}
