name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Manual Deployment Reason'
        required: false
        default: 'Rebuild gatsby'
  push:
    branches:
      - master
      - seo

jobs:
  deploy:
    name: Build and Deploy to AWS S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: yarn build
        env:
          GATSBY_STRAPI_API_URL: ${{ secrets.GATSBY_STRAPI_API_URL }}
          GATSBY_S3_BUCKET: ${{ secrets.S3_BUCKET_PROD }}
          GATSBY_SITE_URL: 'https://barmaga.io'
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_GOOGLE_ANALYTICS_ID: ${{ secrets.GATSBY_GOOGLE_ANALYTICS_ID }}
      - name: Deploy website
        run: yarn deploy
  invalidate:
    name: Invalidate cloudfront cache
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Invalidate cache
        run: aws cloudfront create-invalidation --distribution-id "${{ secrets.CLOUD_FRONT_PROD_DISTRIBUTION }}" --paths "/*"
