name: Syntax and Linting

on: [pull_request]

jobs:
  lint-and-test:
    name: Syntax check (Eslint) and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Run Eslint
        run: yarn lint
      - name: Run Tests
        run: yarn test
      - name: Build website
        run: yarn build
        env:
          GATSBY_STRAPI_API_URL: ${{ secrets.GATSBY_STRAPI_API_URL }}
          GATSBY_S3_BUCKET: ${{ secrets.S3_BUCKET_PROD }}
          GATSBY_SITE_URL: 'https://barmaga.io'
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_GOOGLE_ANALYTICS_ID: ${{ secrets.GATSBY_GOOGLE_ANALYTICS_ID }}
